[workspace]
name = "media-tracking-ml"
version = "0.1.0"
description = "Media tracking ML research"
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64", "win-64"]

[feature.base.dependencies]
python = "3.11.*"
jupyterlab = "*"
ipykernel = "*"
ipywidgets = "*"

[feature.base.pypi-dependencies]
matplotlib = "*"
seaborn = "*"
joblib = "*"
tqdm = "*"
fastparquet = "*"
setuptools = "*"
sentence-transformers = "*"
umap-learn = "*"
hdbscan = "*"
pymorphy3 = "*"
pymorphy2-dicts-ru = "*"
razdel = "*"
huggingface-hub = "*"
bertopic = "*"
gensim = "*"
optuna = "*"
clearml = "*"
python-dotenv = "*"
openai = "*"
scikit-learn = "*"
numpy = ">=2.0"
pandas = ">=2.0"
scipy = ">=1.14"
pynndescent = ">=0.5.13"

[feature.cuda.pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cu130" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu130" }
pyarrow = ">=24.0.0, <25"

[feature.cpu.pypi-dependencies]
torch = "*"
torchvision = "*"
pyarrow = ">=24.0.0, <25"

[environments]
cuda = { features = ["base", "cuda"], solve-group = "cuda" }
cpu = { features = ["base", "cpu"], solve-group = "cpu" }

[dependencies]
ruff = ">=0.15.11,<0.16"

[feature.base.tasks]
lab = "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser"
